apiVersion: v1
kind: Secret
metadata:
  name: food-delivery-backend-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: YOUR_MONGODB_USERNAME
  MONGO_INITDB_ROOT_PASSWORD: YOUR_MONGODB_PASSWORD
  MONGO_URL: mongodb://YOUR_MONGODB_USERNAME:YOUR_MONGODB_PASSWORD@food-delivery-mongodb-service:27017/food-del?authSource=admin